---
title: test3: prioritized search graph
---
flowchart LR
    phone_01["phone_01<br/>cell phone<br/>Hop 0"]
    entity_0059["entity_0059<br/>chair<br/>Hop 1"]
    entity_0051["entity_0051<br/>sports ball<br/>Hop 1"]
    entity_0054["entity_0054<br/>microwave<br/>Hop 2"]
    entity_0053["entity_0053<br/>chair<br/>Hop 1"]
    entity_0020["entity_0020<br/>chair<br/>Hop 1"]
    r1(["SEARCH #1
NEAR<br/>CANDIDATE<br/>LAST_TRUSTED"])
    phone_01 --> r1
    r1 --> entity_0059
    r2(["SEARCH #2
NEAR<br/>CANDIDATE<br/>LAST_TRUSTED"])
    phone_01 --> r2
    r2 --> entity_0051
    r3(["IMAGE_NEAR_CONTEXT<br/>CONTEXT"])
    entity_0051 --> r3
    r3 --> entity_0054
    r4(["SEARCH #3
NEAR<br/>CANDIDATE<br/>LAST_TRUSTED"])
    phone_01 --> r4
    r4 --> entity_0053
    r5(["SEARCH #4
NEAR<br/>CANDIDATE<br/>LAST_TRUSTED"])
    phone_01 --> r5
    r5 --> entity_0020
    classDef target stroke-width:4px,font-weight:bold;
    classDef relation stroke-dasharray: 4 2;
    class phone_01 target;
    class r1,r2,r3,r4,r5 relation;
