---
title: phone_01 search graph
---
flowchart LR
    phone_01["phone_01<br/>cell phone<br/>Hop 0"]
    entity_0022["entity_0022<br/>cup<br/>Hop 1"]
    entity_0023["entity_0023<br/>bottle<br/>Hop 1"]
    entity_0024["entity_0024<br/>cup<br/>Hop 1"]
    entity_0029["entity_0029<br/>cup<br/>Hop 1"]
    entity_0031["entity_0031<br/>chair<br/>Hop 1"]
    entity_0033["entity_0033<br/>table<br/>Hop 1"]
    entity_0037["entity_0037<br/>chair<br/>Hop 1"]
    entity_0026["entity_0026<br/>chair<br/>Hop 2"]
    entity_0027["entity_0027<br/>chair<br/>Hop 2"]
    entity_0032["entity_0032<br/>tv<br/>Hop 2"]
    entity_0034["entity_0034<br/>refrigerator<br/>Hop 2"]
    entity_0040["entity_0040<br/>baseball glove<br/>Hop 1"]
    entity_0043["entity_0043<br/>chair<br/>Hop 1"]
    entity_0045["entity_0045<br/>chair<br/>Hop 1"]
    entity_0025["entity_0025<br/>chair<br/>Hop 1"]
    entity_0042["entity_0042<br/>cup<br/>Hop 1"]
    r1(["TRUSTED_ANCHOR_CONTEXT<br/>LAST_TRUSTED"])
    phone_01 --> r1
    r1 --> entity_0022
    r2(["TRUSTED_ANCHOR_CONTEXT<br/>LAST_TRUSTED"])
    phone_01 --> r2
    r2 --> entity_0023
    r3(["TRUSTED_ANCHOR_CONTEXT<br/>LAST_TRUSTED"])
    phone_01 --> r3
    r3 --> entity_0037
    r4(["IMAGE_NEAR_CONTEXT<br/>LAST_TRUSTED"])
    entity_0022 --> r4
    r4 --> entity_0026
    r5(["IMAGE_NEAR_CONTEXT<br/>LAST_TRUSTED"])
    entity_0023 --> r5
    r5 --> entity_0032
    r6(["IMAGE_NEAR_CONTEXT<br/>LAST_TRUSTED"])
    entity_0023 --> r6
    r6 --> entity_0034
    r7(["IMAGE_NEAR_CONTEXT<br/>LAST_TRUSTED"])
    entity_0037 --> r7
    r7 --> entity_0032
    r8(["IMAGE_NEAR_CONTEXT<br/>LAST_TRUSTED"])
    entity_0037 --> r8
    r8 --> entity_0034
    r9(["NEAR<br/>CANDIDATE<br/>LAST_TRUSTED"])
    phone_01 --> r9
    r9 --> entity_0023
    r10(["NEAR<br/>CANDIDATE<br/>LAST_TRUSTED"])
    phone_01 --> r10
    r10 --> entity_0023
    r11(["NEAR<br/>CANDIDATE<br/>LAST_TRUSTED"])
    phone_01 --> r11
    r11 --> entity_0026
    r12(["NEAR<br/>CANDIDATE<br/>LAST_TRUSTED"])
    phone_01 --> r12
    r12 --> entity_0040
    r13(["NEAR<br/>CANDIDATE<br/>LAST_TRUSTED"])
    phone_01 --> r13
    r13 --> entity_0043
    r14(["NEAR<br/>CANDIDATE<br/>LAST_TRUSTED"])
    phone_01 --> r14
    r14 --> entity_0037
    r15(["NEAR<br/>CANDIDATE<br/>LAST_TRUSTED"])
    phone_01 --> r15
    r15 --> entity_0045
    r16(["NEAR<br/>CANDIDATE<br/>LAST_TRUSTED"])
    phone_01 --> r16
    r16 --> entity_0025
    r17(["NEAR<br/>CANDIDATE<br/>LAST_TRUSTED"])
    phone_01 --> r17
    r17 --> entity_0042
    classDef target stroke-width:4px,font-weight:bold;
    classDef relation stroke-dasharray: 4 2;
    class phone_01 target;
    class r1,r2,r3,r4,r5,r6,r7,r8,r9,r10,r11,r12,r13,r14,r15,r16,r17 relation;
