---
title: phone_01 lifetime memory
---
flowchart LR
    phone_01["phone_01<br/>cell phone<br/>Hop 0"]
    entity_0024["entity_0024<br/>microwave<br/>Hop 1"]
    entity_0028["entity_0028<br/>sports ball<br/>Hop 1"]
    entity_0030["entity_0030<br/>chair<br/>Hop 1"]
    entity_0034["entity_0034<br/>potted plant<br/>Hop 2"]
    classDef target stroke-width:4px,font-weight:bold;
    classDef relation stroke-dasharray: 4 2;
    class phone_01 target;
